
 <meta charset="utf-8">
<title>jQuery UI Dialog - Animation</title>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<!-- Js -->            
<?php  $this->headScript()
            ->appendFile($this->basePath() . '/js/ajaxform.js'); ?>
<script>
</script>
</head>
<body>
<a  id="showform" href="/testajax/skeleton/showform">Show Form2</a>
<!-- empty div to save dialog temporary -->
<div id="winpopup"></div>
</body>