<?php /*
echo '<h1>Izmena imena zaposlenog</h1>';
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('application/default', array('controller' => 'Index', 'action' => 'EditEmployee'))); 

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();


*/
$title = 'Edit Employee';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<form method="post">
  Ime i prezime: <input type="text" name="name" value="<?php echo $employee->getName(); ?>"><br>
  <input type="submit" value="Submit">
</form>