<?php
echo '<h2>Zaposleni</h1>';
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('application/default', array('controller' => 'Index', 'action' => 'employee'))); 

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
if (isset($employees)) : ?>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Ime</th>
            <th></th>
        </tr>
        </thead>
    <?php foreach($employees as $employee): ?>
        <tbody>
        <tr>
            <td><?php echo $employee->getId(); ?></td>
            <td><?php echo $employee->getName(); ?></td>
            <td>
                <a href="<?php echo $this->url('application/default', array('controller' => 'Index','action'=>'EditEmployee', 'id' => $employee->getId()));?>">Izmeni</a> |
                <a href="<?php echo $this->url('application/default', array('controller' => 'Index','action'=>'DeleteEmployee', 'id' => $employee->getId()));?>">Obriši</a>
            </td>
        </tr>
        </tbody>
    <?php endforeach; ?>
    </table>
    <?php endif; ?>
