<div>
    <h3>Događaji</h3>
</div>
<div>
    <a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'add'));?>">Add Event</a>

    <?php if (isset($events)) : ?>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Ime dogadjaja</th>
            <th></th>
        </tr>
        </thead>
    <?php foreach($events as $event): ?>
        <tbody>
        <tr>
            <td><?php echo $event->getId(); ?></td>
            <td><?php echo $event->getName(); ?></td>
            <td>
                <a href="<?php echo $this->url('application/default', array('action'=>'edit', 'id' => $event->getId()));?>">Edit</a> |
                <a href="<?php echo $this->url('application/default', array('action'=>'delete', 'id' => $event->getId()));?>">Delete</a>
            </td>
        </tr>
        </tbody>
    <?php endforeach; ?>
    </table>
    <?php endif; ?>
</div>