<div>
    <h3>Prikaz svih događaja od prvog u sadašnjem mesecu</h3>
</div>
<div>
    <a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'addEvent'));?>">Dodaj događaj</a>

    <?php if (isset($events)) : ?>
    <table>
        <thead>
        <tr>
            <th>Program</th>
            <th>Ime događaja</th>
            <th></th>
        </tr>
        </thead>
    <?php foreach($events as $event): ?>
        <tbody>
        <tr>
            <td style='padding: 5px'><?php echo $event->getRedaction(); ?></td>
            <td style='padding: 5px'><?php echo $event->getName(); ?></td>
            <td>
                <a href="<?php echo $this->url('application/default', array('controller' => 'Index','action'=>'EditEvent', 'id' => $event->getId()));?>">Izmeni</a> |
                <a href="<?php echo $this->url('application/default', array('controller' => 'Index','action'=>'DeleteEvent', 'id' => $event->getId()));?>">Obriši</a>
            </td>
        </tr>
        </tbody>
    <?php endforeach; ?>
    </table>
    <?php endif; ?>
</div>